### ISSUE TITLE
批量压缩文件时出现大量报错Too many files uploaded at once

### ISSUE THREAD

**Issue by Smile8848** [libudu/ultra-tinypng#1]
Too many files uploaded at once

**Comment by mycpen** [comment]
同样的报错：`压缩失败！报错：Too many files uploaded at once.`

<img width="768" alt="Snipaste_2023-07-10_16-26-52" src="https://github.com/libudu/ultra-tinypng/assets/72154342/c2376b86-c9f7-4d5b-8e42-034d3a42824b">

**Comment by libudu** [comment]
tinypng后台改变了接口判断策略，原先仅通过ip来确定请求是否来自同一主机，现在还通过了其他方法来确定。目前频率大概至少5秒一次请求才不会被拦截
解决方法：
1、将20线程降低为单线程，且每次请求至少间隔5秒
2、尝试探索是tingpng后台是怎么确定不同请求来自同一主机的，并尝试绕过该策略

**Comment by libudu** [comment]
查了一些资料，做了一些尝试
1、尝试伪造x-real-ip、origin请求头，没有用
2、本地先启动一个服务，大概前面15个请求正常，开始报错后立刻再起一个服务，立刻一起开始报错。可能说明和session无关
3、怀疑可能是通过Remote Address判断多个请求是否来自同一主机的。可以通过设置代理服务器来测试但是太麻烦了
关于Remote Address的资料：http://www.manongjc.com/detail/25-qfsapnipylelmyj.html
如果真的使用Remote Address检测的话那基本没办法了，只能降低频率到5秒一次

**Comment by libudu** [comment]
降低频率到单线程且间隔5秒一次，可以不间断运行
